TWIT_POSTED = "_TWIT_P"
TWIT_QUEUED = "_TWIT_Q"

DEVI_POSTED = "_DEVI_P"
DEVI_QUEUED = "_DEVI_Q"

TAG_MAPPING = {"Twitter": "TWIT", "Deviant": "DEVI"}

QUEUE_TAG_MAPPING = {"Twitter": TWIT_QUEUED, "Deviant": DEVI_QUEUED}

POSTED_TAG_MAPPING = {"Twitter": TWIT_POSTED, "Deviant": DEVI_POSTED}
